server:
  port: 8081

spring:
  application:
    name: ORDER-SERVICE
  datasource:
    url: jdbc:postgresql://microservices.cz2om8iwk6mb.us-east-2.rds.amazonaws.com:5432/microservices
    username: postgres
    password: 57eAu4X4qIgkpuBLqOwS
    hikari:
      schema: order
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    enabled: true

feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 5000
        retryer:
          period: 1000       # Tiempo entre reintentos (ms)
          max-period: 2000   # Tiempo máximo entre reintentos (ms)
          max-attempts: 3

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    feign: DEBUG